{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled .Values.mongodb.auth.rootPassword -}}
{{- if not .Values.mongodb.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
{{- end }}
