{{- if and .Values.mongodb.enabled .Values.mongodb.auth.enabled -}}
{{- if not .Values.mongodb.auth.existingSecret }}
{{- if not .Values.mongodb.auth.rootPassword }}
{{- fail "MongoDB root password must be provided via mongodb.auth.rootPassword or mongodb.auth.existingSecret when auth is enabled" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
{{- end }}
{{- end }}
