{{- if .Values.nomad.enabled -}}
{{- $config := .Values.nomad.config -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-cpuworker
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: cpuworker
spec:
  replicas: {{ .Values.nomad.cpuworker.replicaCount }}
  selector:
    matchLabels:
      {{- include "nomad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cpuworker
  template:
    metadata:
      {{- with .Values.nomad.cpuworker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if $.Values.roll }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- else }}
      {{- if .Values.roll }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "nomad.labels" . | nindent 8 }}
        {{- with .Values.nomad.cpuworker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: cpuworker
    spec:
      {{- with .Values.nomad.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nomad.serviceAccountName" . }}
      enableServiceLinks: false
      {{- with .Values.nomad.cpuworker.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-cpuworker
          {{- with .Values.nomad.cpuworker.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.nomad.cpuworker.image.repository }}
          image: "{{ .Values.nomad.cpuworker.image.repository }}:{{ .Values.nomad.cpuworker.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.nomad.image.repository }}:{{ .Values.nomad.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.nomad.image.pullPolicy }}
          {{- with .Values.nomad.cpuworker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/nomad.yaml
              name: nomad-conf
              subPath: nomad.yaml
            - mountPath: /app/.volumes/fs/public
              name: public-volume
            - mountPath: /app/.volumes/fs/staging
              name: staging-volume
            - mountPath: /nomad
              name: nomad-volume
            {{- with .Values.nomad.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.nomad.cpuworker.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: MPLCONFIGDIR
              value: /tmp/matplotlib

            - name: NOMAD_META_SERVICE
              value: "worker"
            - name: NOMAD_CONSOLE_LOG_LEVEL
              value: "{{ $config.logging.worker.console_loglevel }}"
            - name: NOMAD_LOGSTASH_LEVEL
              value: "{{ $config.logging.worker.logstash_loglevel }}"

            {{- if .Values.nomad.secrets.api.secretName }}
            - name: NOMAD_SERVICES_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.api.secretName }}
                  key: password
            {{- end }}
            {{- if .Values.nomad.secrets.keycloak.clientSecretName }}
            - name: NOMAD_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.keycloak.clientSecretName }}
                  key: password
            {{- end }}
            {{- if .Values.nomad.secrets.keycloak.passwordSecretName }}
            - name: NOMAD_KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.nomad.secrets.keycloak.passwordSecretName }}
                  key: password
            {{- end }}
          # See https://keithtenzer.com/temporal/Deploying_Temporal_Worker_on_Kubernetes/#liveliness-and-readiness-probes
          # for rationale on using 'ls /' as a liveness/readiness probe for Temporal workers.
          command: ["python", "-m", "nomad.cli", "admin", "run", "action-cpu-worker"]
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - "ls /"
            initialDelaySeconds: {{ .Values.nomad.cpuworker.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nomad.cpuworker.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nomad.cpuworker.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.nomad.cpuworker.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.nomad.cpuworker.livenessProbe.successThreshold | default 1 }}
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -ec
              - "ls /"
            initialDelaySeconds: {{ .Values.nomad.cpuworker.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nomad.cpuworker.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nomad.cpuworker.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.nomad.cpuworker.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.nomad.cpuworker.readinessProbe.successThreshold | default 1 }}
      volumes:
      {{- with .Values.nomad.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.cpuworker.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: nomad-conf
          configMap:
            name: {{ include "nomad.fullname" . }}-configmap
        {{- include "nomad.dataVolume" (dict "root" . "name" "public-volume" "volumeKey" "public" "hostPath" $config.fs.public_external) | nindent 8 }}
        {{- if (eq .Values.nomad.worker.storage "memory") }}
        - name: staging-volume
          emptyDir:
            medium: 'Memory'
        {{- else }}
        {{- include "nomad.dataVolume" (dict "root" . "name" "staging-volume" "volumeKey" "staging" "hostPath" $config.fs.staging_external) | nindent 8 }}
        {{- end }}
        {{- include "nomad.dataVolume" (dict "root" . "name" "nomad-volume" "volumeKey" "nomad" "hostPath" $config.fs.nomad) | nindent 8 }}

      {{- with .Values.nomad.cpuworker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.cpuworker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.cpuworker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
