{{- if .Values.nomad.adminconsole.enabled -}}
{{- $config := .Values.nomad.config -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nomad.fullname" . }}-adminconsole
  labels:
    {{- include "nomad.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminconsole
spec:
  replicas: {{ .Values.nomad.adminconsole.replicaCount }}
  selector:
    matchLabels:
      {{- include "nomad.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: adminconsole
  template:
    metadata:
      {{- with .Values.nomad.adminconsole.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- if $.Values.roll }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- end }}
      {{- else }}
      {{- if .Values.roll }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
      {{- end }}
      labels:
        {{- include "nomad.labels" . | nindent 8 }}
        {{- with .Values.nomad.adminconsole.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: adminconsole
    spec:
      {{- with .Values.nomad.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nomad.serviceAccountName" . }}
      enableServiceLinks: false
      {{- with .Values.nomad.adminconsole.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-adminconsole
          {{- with .Values.nomad.adminconsole.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.nomad.image.repository }}:{{ .Values.nomad.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nomad.image.pullPolicy }}
          {{- with .Values.nomad.adminconsole.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /app/nomad.yaml
              name: nomad-conf
              subPath: nomad.yaml
            - mountPath: /app/.volumes/fs/public
              name: public-volume
            - mountPath: /app/.volumes/fs/staging
              name: staging-volume
            - mountPath: /nomad
              name: nomad-volume
            {{- with .Values.nomad.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.nomad.adminconsole.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: JUPYTER_RUNTIME_DIR
              value: /tmp
            - name: JUPYTER_DATA_DIR
              value: /tmp

            - name: NOMAD_META_SERVICE
              value: "adminconsole"
            - name: NOMAD_CONSOLE_LOG_LEVEL
              value: "{{ $config.logging.worker.console_loglevel }}"
            - name: NOMAD_LOGSTASH_LEVEL
              value: "{{ $config.logging.worker.logstash_loglevel }}"

            {{- if or .Values.nomad.secrets.api.existingSecret .Values.nomad.secrets.api.value .Values.nomad.secrets.api.autoGenerate }}
            - name: NOMAD_SERVICES_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nomad.secretName.api" . }}
                  key: {{ .Values.nomad.secrets.api.key }}
            {{- end }}
            {{- if or .Values.nomad.secrets.keycloak.clientSecret.existingSecret .Values.nomad.secrets.keycloak.clientSecret.value }}
            - name: NOMAD_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "nomad.secretName.keycloakClient" . }}
                  key: {{ .Values.nomad.secrets.keycloak.clientSecret.key }}
            {{- end }}
            {{- if or .Values.nomad.secrets.keycloak.password.existingSecret .Values.nomad.secrets.keycloak.password.value }}
            - name: NOMAD_KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "nomad.secretName.keycloakPassword" . }}
                  key: {{ .Values.nomad.secrets.keycloak.password.key }}
            {{- end }}
          command: ["jupyter", "lab", "--notebook-dir", "/nomad/adminconsole"]
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - ls /
            failureThreshold: {{ .Values.nomad.adminconsole.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.nomad.adminconsole.livenessProbe.successThreshold | default 1 }}
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - ls /
            initialDelaySeconds: {{ .Values.nomad.adminconsole.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.nomad.adminconsole.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.nomad.adminconsole.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.nomad.adminconsole.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.nomad.adminconsole.readinessProbe.successThreshold | default 1 }}
      volumes:
      {{- with .Values.nomad.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.adminconsole.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: nomad-conf
          configMap:
            name: {{ include "nomad.fullname" . }}-configmap
        {{- include "nomad.dataVolume" (dict "root" . "name" "public-volume" "volumeKey" "public" "hostPath" $config.fs.public_external) | nindent 8 }}
        {{- if (eq .Values.nomad.worker.storage "memory") }}
        - name: staging-volume
          emptyDir:
            medium: 'Memory'
        {{- else }}
        {{- include "nomad.dataVolume" (dict "root" . "name" "staging-volume" "volumeKey" "staging" "hostPath" $config.fs.staging_external) | nindent 8 }}
        {{- end }}
        {{- include "nomad.dataVolume" (dict "root" . "name" "nomad-volume" "volumeKey" "nomad" "hostPath" $config.fs.nomad) | nindent 8 }}

      {{- with .Values.nomad.adminconsole.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.adminconsole.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nomad.adminconsole.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
